console.log("java Running");
alert("Hello User!")
var num1=12;
var num2=38;
console.log(num1 + num2)
console.log(num1 - num2)
console.log(num1 * num2)
console.log(num1 / num2)
console.log(num1 % num2)
var num = 1;
num++
console.log( num )
let name = "My_Name I$ Mu/hammad B8ilal"
console.log(name)
 var num3 =4;
 var newnum =--num3
 console.log(--newnum)
  prompt("Enter Your  Comand")
  var englishtotal=100;
  var urdutotal=100;
  var mathstotal=100;
  console.log (englishtotal+urdutotal+mathstotal)
   let englishobt=52;
  let urduobt=52;
  let mathsobt=48;
  console.log(englishobt+urduobt+mathsobt)
  let englishpercent=52
  let urdupercent=52
  let mathspercent=48
  console.log(englishpercent%urdupercent%mathspercent)
